# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.4.7-rdg
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.motivation_get_dto import MotivationGetDTO
from typing import Optional, Set
from typing_extensions import Self

class AnnotationGetDTO(BaseModel):
    """
    AnnotationGetDTO
    """ # noqa: E501
    uri: Optional[StrictStr] = Field(default=None, description="Annotation URI")
    description: Optional[StrictStr] = Field(default=None, description="Content of the annotation")
    targets: Optional[List[StrictStr]] = None
    motivation: Optional[MotivationGetDTO] = None
    published: Optional[datetime] = None
    publisher: Optional[StrictStr] = Field(default=None, description="Annotation publisher URI")
    __properties: ClassVar[List[str]] = ["uri", "description", "targets", "motivation", "published", "publisher"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AnnotationGetDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of motivation
        if self.motivation:
            _dict['motivation'] = self.motivation.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AnnotationGetDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "uri": obj.get("uri"),
            "description": obj.get("description"),
            "targets": obj.get("targets"),
            "motivation": MotivationGetDTO.from_dict(obj["motivation"]) if obj.get("motivation") is not None else None,
            "published": obj.get("published"),
            "publisher": obj.get("publisher")
        })
        return _obj


