# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.4.7-rdg
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.count_item_dto import CountItemDTO
from openapi_client.models.count_item_period_dto import CountItemPeriodDTO
from typing import Optional, Set
from typing_extensions import Self

class CountListItemPeriodDTO(BaseModel):
    """
    CountListItemPeriodDTO
    """ # noqa: E501
    total_difference_item_count: Optional[StrictInt] = None
    difference_items: Optional[List[CountItemPeriodDTO]] = None
    name: Optional[StrictStr] = None
    type: Optional[StrictStr] = None
    total_items_count: Optional[StrictInt] = None
    items: Optional[List[CountItemDTO]] = None
    __properties: ClassVar[List[str]] = ["total_difference_item_count", "difference_items", "name", "type", "total_items_count", "items"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CountListItemPeriodDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in difference_items (list)
        _items = []
        if self.difference_items:
            for _item_difference_items in self.difference_items:
                if _item_difference_items:
                    _items.append(_item_difference_items.to_dict())
            _dict['difference_items'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in items (list)
        _items = []
        if self.items:
            for _item_items in self.items:
                if _item_items:
                    _items.append(_item_items.to_dict())
            _dict['items'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CountListItemPeriodDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "total_difference_item_count": obj.get("total_difference_item_count"),
            "difference_items": [CountItemPeriodDTO.from_dict(_item) for _item in obj["difference_items"]] if obj.get("difference_items") is not None else None,
            "name": obj.get("name"),
            "type": obj.get("type"),
            "total_items_count": obj.get("total_items_count"),
            "items": [CountItemDTO.from_dict(_item) for _item in obj["items"]] if obj.get("items") is not None else None
        })
        return _obj


