# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.4.7-rdg
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.provenance_get_dto import ProvenanceGetDTO

class TestProvenanceGetDTO(unittest.TestCase):
    """ProvenanceGetDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProvenanceGetDTO:
        """Test ProvenanceGetDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProvenanceGetDTO`
        """
        model = ProvenanceGetDTO()
        if include_optional:
            return ProvenanceGetDTO(
                uri = 'http://provenance/prov01',
                name = 'air_temperature_acquisition',
                description = 'acquisition of air temperature with sensor 01',
                prov_activity = [
                    openapi_client.models.activity_get_dto.ActivityGetDTO(
                        rdf_type = 'oeso:ImageAcquisition', 
                        uri = '', 
                        start_date = '2020-08-21T00:00:00+01:00', 
                        end_date = '2020-09-21T00:00:00+01:00', 
                        settings = {
                            'key' : None
                            }, )
                    ],
                prov_agent = [
                    openapi_client.models.agent_model.AgentModel(
                        uri = 'http://sensor/s01', 
                        rdf_type = 'oeso:Sensor', 
                        settings = {
                            'key' : None
                            }, )
                    ],
                publisher = openapi_client.models.user_get_dto.UserGetDTO(
                    uri = 'http://opensilex.dev/users#jean.michel.inrae', 
                    email = 'jean.michel@example.com', 
                    language = 'en', 
                    admin = False, 
                    first_name = 'Jean', 
                    last_name = 'Michel', 
                    linked_person = 'http://opensilex.dev/person#Jean.Michel.mistea', 
                    enable = True, 
                    favorites = test, ),
                issued = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ProvenanceGetDTO(
                name = 'air_temperature_acquisition',
        )
        """

    def testProvenanceGetDTO(self):
        """Test ProvenanceGetDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
