# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.4.7-rdg
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.species_api import SpeciesApi


class TestSpeciesApi(unittest.TestCase):
    """SpeciesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SpeciesApi()

    def tearDown(self) -> None:
        pass

    def test_get_all_species(self) -> None:
        """Test case for get_all_species

        get species (no pagination)
        """
        pass


if __name__ == '__main__':
    unittest.main()
