# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.4.7-rdg
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.faidarev1_trait_dto import Faidarev1TraitDTO

class TestFaidarev1TraitDTO(unittest.TestCase):
    """Faidarev1TraitDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Faidarev1TraitDTO:
        """Test Faidarev1TraitDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Faidarev1TraitDTO`
        """
        model = Faidarev1TraitDTO()
        if include_optional:
            return Faidarev1TraitDTO(
                trait_db_id = '',
                name = '',
                description = '',
                synonyms = [
                    ''
                    ],
                main_abbreviation = '',
                alternative_abbreviations = [
                    ''
                    ],
                entity = '',
                attribute = '',
                status = '',
                xref = '',
                var_class = ''
            )
        else:
            return Faidarev1TraitDTO(
        )
        """

    def testFaidarev1TraitDTO(self):
        """Test Faidarev1TraitDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
