# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.4.7-rdg
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.owl_class_property_restriction_dto import OWLClassPropertyRestrictionDTO

class TestOWLClassPropertyRestrictionDTO(unittest.TestCase):
    """OWLClassPropertyRestrictionDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OWLClassPropertyRestrictionDTO:
        """Test OWLClassPropertyRestrictionDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OWLClassPropertyRestrictionDTO`
        """
        model = OWLClassPropertyRestrictionDTO()
        if include_optional:
            return OWLClassPropertyRestrictionDTO(
                required = True,
                list = True,
                rdf_type = 'vocabulary:Plot',
                domain = 'vocabulary:ScientificObject',
                var_property = 'vocabulary:hasGermplasm'
            )
        else:
            return OWLClassPropertyRestrictionDTO(
                rdf_type = 'vocabulary:Plot',
                domain = 'vocabulary:ScientificObject',
                var_property = 'vocabulary:hasGermplasm',
        )
        """

    def testOWLClassPropertyRestrictionDTO(self):
        """Test OWLClassPropertyRestrictionDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
