# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.4.7-rdg
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.faidarev1_trial_additional_info_dto import Faidarev1TrialAdditionalInfoDTO

class TestFaidarev1TrialAdditionalInfoDTO(unittest.TestCase):
    """Faidarev1TrialAdditionalInfoDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Faidarev1TrialAdditionalInfoDTO:
        """Test Faidarev1TrialAdditionalInfoDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Faidarev1TrialAdditionalInfoDTO`
        """
        model = Faidarev1TrialAdditionalInfoDTO()
        if include_optional:
            return Faidarev1TrialAdditionalInfoDTO(
                short_name = '',
                description = '',
                financial_funding = '',
                related_projects = [
                    ''
                    ],
                coordinators = [
                    openapi_client.models.faidarev1_contact_dto.Faidarev1ContactDTO(
                        contact_db_id = '', 
                        email = '', 
                        institution_name = '', 
                        name = '', 
                        orcid = '', 
                        type = '', )
                    ]
            )
        else:
            return Faidarev1TrialAdditionalInfoDTO(
        )
        """

    def testFaidarev1TrialAdditionalInfoDTO(self):
        """Test Faidarev1TrialAdditionalInfoDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
