# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.4.7-rdg
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.user_update_dto import UserUpdateDTO

class TestUserUpdateDTO(unittest.TestCase):
    """UserUpdateDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserUpdateDTO:
        """Test UserUpdateDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserUpdateDTO`
        """
        model = UserUpdateDTO()
        if include_optional:
            return UserUpdateDTO(
                uri = 'http://opensilex.dev/users#jean.michel.inrae',
                first_name = 'Janne',
                language = 'en',
                password = 'azerty',
                admin = False,
                last_name = 'Michelle',
                email = 'jean.michel@example.com',
                enable = True,
                favorites = [
                    ''
                    ],
                linked_person = 'http://opensilex.dev/person#Jean.Michel.mistea'
            )
        else:
            return UserUpdateDTO(
                uri = 'http://opensilex.dev/users#jean.michel.inrae',
                first_name = 'Janne',
                language = 'en',
                admin = False,
                last_name = 'Michelle',
                email = 'jean.michel@example.com',
        )
        """

    def testUserUpdateDTO(self):
        """Test UserUpdateDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
