# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.4.7-rdg
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.brapi_api import BRAPIApi


class TestBRAPIApi(unittest.TestCase):
    """BRAPIApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BRAPIApi()

    def tearDown(self) -> None:
        pass

    def test_get_calls(self) -> None:
        """Test case for get_calls

        Check the available BrAPI calls
        """
        pass

    def test_get_germplasm_by_search(self) -> None:
        """Test case for get_germplasm_by_search

        Submit a search request for germplasm (type accession in OpenSILEX
        """
        pass

    def test_get_observation_units(self) -> None:
        """Test case for get_observation_units

        List all the observation units measured in the study.
        """
        pass

    def test_get_observation_variables(self) -> None:
        """Test case for get_observation_variables

        List all the observation variables measured in the study.
        """
        pass

    def test_get_observations(self) -> None:
        """Test case for get_observations

        Get the observations associated to a specific study
        """
        pass

    def test_get_studies(self) -> None:
        """Test case for get_studies

        Retrieve studies information
        """
        pass

    def test_get_studies_search(self) -> None:
        """Test case for get_studies_search

        Retrieve studies information
        """
        pass

    def test_get_study_details(self) -> None:
        """Test case for get_study_details

        Retrieve study details
        """
        pass

    def test_get_variable_details(self) -> None:
        """Test case for get_variable_details

        Retrieve variable details by id
        """
        pass

    def test_get_variables_list(self) -> None:
        """Test case for get_variables_list

        BrAPIv1CallDTO to retrieve a list of observationVariables available in the system
        """
        pass


if __name__ == '__main__':
    unittest.main()
