# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.4.7-rdg
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.data_file_path_creation_dto import DataFilePathCreationDTO

class TestDataFilePathCreationDTO(unittest.TestCase):
    """DataFilePathCreationDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DataFilePathCreationDTO:
        """Test DataFilePathCreationDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DataFilePathCreationDTO`
        """
        model = DataFilePathCreationDTO()
        if include_optional:
            return DataFilePathCreationDTO(
                uri = '',
                rdf_type = 'http://www.opensilex.org/vocabulary/oeso#Image',
                var_date = '2020-08-21T00:00:00+01:00',
                timezone = 'Europe/Paris',
                target = '',
                provenance = openapi_client.models.data_provenance_model.DataProvenanceModel(
                    uri = 'http://opensilex.dev/id/provenance/provenancelabel', 
                    prov_used = [
                        openapi_client.models.prov_entity_model.ProvEntityModel(
                            uri = '', 
                            rdf_type = '', )
                        ], 
                    prov_was_associated_with = [
                        openapi_client.models.prov_entity_model.ProvEntityModel(
                            uri = '', 
                            rdf_type = '', )
                        ], 
                    settings = {
                        'key' : None
                        }, 
                    experiments = [
                        ''
                        ], ),
                metadata = { "LabelView" : "side90",
"paramA" : "90"},
                archive = '',
                relative_path = 'http://opensilex.dev/id/file/1598857852858'
            )
        else:
            return DataFilePathCreationDTO(
                rdf_type = 'http://www.opensilex.org/vocabulary/oeso#Image',
                provenance = openapi_client.models.data_provenance_model.DataProvenanceModel(
                    uri = 'http://opensilex.dev/id/provenance/provenancelabel', 
                    prov_used = [
                        openapi_client.models.prov_entity_model.ProvEntityModel(
                            uri = '', 
                            rdf_type = '', )
                        ], 
                    prov_was_associated_with = [
                        openapi_client.models.prov_entity_model.ProvEntityModel(
                            uri = '', 
                            rdf_type = '', )
                        ], 
                    settings = {
                        'key' : None
                        }, 
                    experiments = [
                        ''
                        ], ),
                relative_path = 'http://opensilex.dev/id/file/1598857852858',
        )
        """

    def testDataFilePathCreationDTO(self):
        """Test DataFilePathCreationDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
