# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.4.7-rdg
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.security_api import SecurityApi


class TestSecurityApi(unittest.TestCase):
    """SecurityApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SecurityApi()

    def tearDown(self) -> None:
        pass

    def test_add_favorite(self) -> None:
        """Test case for add_favorite

        Add a favorite
        """
        pass

    def test_add_favorite1(self) -> None:
        """Test case for add_favorite1

        Add a favorite
        """
        pass

    def test_create_account(self) -> None:
        """Test case for create_account

        Add an account
        """
        pass

    def test_create_group(self) -> None:
        """Test case for create_group

        Add a group
        """
        pass

    def test_create_person(self) -> None:
        """Test case for create_person

        Add a person
        """
        pass

    def test_create_profile(self) -> None:
        """Test case for create_profile

        Add a profile
        """
        pass

    def test_create_user(self) -> None:
        """Test case for create_user

        Add a user
        """
        pass

    def test_delete_account(self) -> None:
        """Test case for delete_account

        Delete an account
        """
        pass

    def test_delete_favorite(self) -> None:
        """Test case for delete_favorite

        Delete a favorite
        """
        pass

    def test_delete_favorite1(self) -> None:
        """Test case for delete_favorite1

        Delete a favorite
        """
        pass

    def test_delete_group(self) -> None:
        """Test case for delete_group

        Delete a group
        """
        pass

    def test_delete_profile(self) -> None:
        """Test case for delete_profile

        Delete a profile
        """
        pass

    def test_get_account(self) -> None:
        """Test case for get_account

        Get an account
        """
        pass

    def test_get_accounts_by_uri(self) -> None:
        """Test case for get_accounts_by_uri

        Get accounts by their URIs
        """
        pass

    def test_get_all_profiles(self) -> None:
        """Test case for get_all_profiles

        Get all profiles
        """
        pass

    def test_get_favorites(self) -> None:
        """Test case for get_favorites

        Get list of favorites for a user
        """
        pass

    def test_get_favorites1(self) -> None:
        """Test case for get_favorites1

        Get list of favorites for a user
        """
        pass

    def test_get_gdpr_file(self) -> None:
        """Test case for get_gdpr_file

        Get RGPD PDF
        """
        pass

    def test_get_group(self) -> None:
        """Test case for get_group

        Get a group
        """
        pass

    def test_get_groups_by_uri(self) -> None:
        """Test case for get_groups_by_uri

        Get groups by their URIs
        """
        pass

    def test_get_orcid_record(self) -> None:
        """Test case for get_orcid_record

        Get infos from an ORCID
        """
        pass

    def test_get_person(self) -> None:
        """Test case for get_person

        Get a Person
        """
        pass

    def test_get_persons_by_uri(self) -> None:
        """Test case for get_persons_by_uri

        Get persons by their URIs
        """
        pass

    def test_get_profile(self) -> None:
        """Test case for get_profile

        Get a profile
        """
        pass

    def test_get_user(self) -> None:
        """Test case for get_user

        Get a user
        """
        pass

    def test_get_user_groups(self) -> None:
        """Test case for get_user_groups

        Get groups of a user
        """
        pass

    def test_get_user_groups1(self) -> None:
        """Test case for get_user_groups1

        Get groups of a user
        """
        pass

    def test_get_users_by_uri(self) -> None:
        """Test case for get_users_by_uri

        Get users by their URIs
        """
        pass

    def test_search_accounts(self) -> None:
        """Test case for search_accounts

        Search accounts
        """
        pass

    def test_search_groups(self) -> None:
        """Test case for search_groups

        Search groups
        """
        pass

    def test_search_persons(self) -> None:
        """Test case for search_persons

        Search persons
        """
        pass

    def test_search_profiles(self) -> None:
        """Test case for search_profiles

        Search profiles
        """
        pass

    def test_search_users(self) -> None:
        """Test case for search_users

        Search users
        """
        pass

    def test_update_account(self) -> None:
        """Test case for update_account

        Update an account
        """
        pass

    def test_update_group(self) -> None:
        """Test case for update_group

        Update a group
        """
        pass

    def test_update_person(self) -> None:
        """Test case for update_person

        Update a person
        """
        pass

    def test_update_profile(self) -> None:
        """Test case for update_profile

        Update a profile
        """
        pass

    def test_update_user(self) -> None:
        """Test case for update_user

        Update a user
        """
        pass


if __name__ == '__main__':
    unittest.main()
