# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.4.7-rdg
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.agent_model import AgentModel

class TestAgentModel(unittest.TestCase):
    """AgentModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentModel:
        """Test AgentModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentModel`
        """
        model = AgentModel()
        if include_optional:
            return AgentModel(
                uri = 'http://sensor/s01',
                rdf_type = 'oeso:Sensor',
                settings = {
                    'key' : None
                    }
            )
        else:
            return AgentModel(
        )
        """

    def testAgentModel(self):
        """Test AgentModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
