# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.4.7-rdg
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.scientific_object_creation_dto import ScientificObjectCreationDTO

class TestScientificObjectCreationDTO(unittest.TestCase):
    """ScientificObjectCreationDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScientificObjectCreationDTO:
        """Test ScientificObjectCreationDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScientificObjectCreationDTO`
        """
        model = ScientificObjectCreationDTO()
        if include_optional:
            return ScientificObjectCreationDTO(
                uri = 'http://opensilex.org/id/Plot 12',
                rdf_type = 'vocabulary:Plot',
                name = 'Plot 12',
                experiment = 'http://opensilex/experiment/id/ZA17',
                relations = [
                    openapi_client.models.rdf_object_relation_dto.RDFObjectRelationDTO(
                        property = '', 
                        value = '', 
                        inverse = True, )
                    ],
                geometry = {"coordinates":[43.618316,3.856912],"type":"Point"},
                publisher = openapi_client.models.user_get_dto.UserGetDTO(
                    uri = 'http://opensilex.dev/users#jean.michel.inrae', 
                    email = 'jean.michel@example.com', 
                    language = 'en', 
                    admin = False, 
                    first_name = 'Jean', 
                    last_name = 'Michel', 
                    linked_person = 'http://opensilex.dev/person#Jean.Michel.mistea', 
                    enable = True, 
                    favorites = test, ),
                publication_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ScientificObjectCreationDTO(
                rdf_type = 'vocabulary:Plot',
                name = 'Plot 12',
        )
        """

    def testScientificObjectCreationDTO(self):
        """Test ScientificObjectCreationDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
