# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.4.7-rdg
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.staple_api_api import StapleAPIApi


class TestStapleAPIApi(unittest.TestCase):
    """StapleAPIApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StapleAPIApi()

    def tearDown(self) -> None:
        pass

    def test_export_ontology_file(self) -> None:
        """Test case for export_ontology_file

        Export ontology file for Staple API as turtle syntax
        """
        pass

    def test_get_resource_graphs(self) -> None:
        """Test case for get_resource_graphs

        Get all graphs associated with resources
        """
        pass


if __name__ == '__main__':
    unittest.main()
