# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.4.7-rdg
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.annotations_api import AnnotationsApi


class TestAnnotationsApi(unittest.TestCase):
    """AnnotationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AnnotationsApi()

    def tearDown(self) -> None:
        pass

    def test_count_annotations(self) -> None:
        """Test case for count_annotations

        Count annotations
        """
        pass

    def test_create_annotation(self) -> None:
        """Test case for create_annotation

        Create an annotation
        """
        pass

    def test_delete_annotation(self) -> None:
        """Test case for delete_annotation

        Delete an annotation
        """
        pass

    def test_get_annotation(self) -> None:
        """Test case for get_annotation

        Get an annotation
        """
        pass

    def test_search_annotations(self) -> None:
        """Test case for search_annotations

        Search annotations
        """
        pass

    def test_search_motivations(self) -> None:
        """Test case for search_motivations

        Search motivations
        """
        pass

    def test_update_annotation(self) -> None:
        """Test case for update_annotation

        Update an annotation
        """
        pass


if __name__ == '__main__':
    unittest.main()
