# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.4.7-rdg
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.activity_get_dto import ActivityGetDTO

class TestActivityGetDTO(unittest.TestCase):
    """ActivityGetDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActivityGetDTO:
        """Test ActivityGetDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActivityGetDTO`
        """
        model = ActivityGetDTO()
        if include_optional:
            return ActivityGetDTO(
                rdf_type = 'oeso:ImageAcquisition',
                uri = '',
                start_date = '2020-08-21T00:00:00+01:00',
                end_date = '2020-09-21T00:00:00+01:00',
                settings = {
                    'key' : None
                    }
            )
        else:
            return ActivityGetDTO(
        )
        """

    def testActivityGetDTO(self):
        """Test ActivityGetDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
