# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.4.7-rdg
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.data_serie_get_dto import DataSerieGetDTO

class TestDataSerieGetDTO(unittest.TestCase):
    """DataSerieGetDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DataSerieGetDTO:
        """Test DataSerieGetDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DataSerieGetDTO`
        """
        model = DataSerieGetDTO()
        if include_optional:
            return DataSerieGetDTO(
                provenance = openapi_client.models.data_simple_provenance_get_dto.DataSimpleProvenanceGetDTO(
                    uri = '', 
                    rdf_type = '', 
                    name = '', ),
                data = [
                    openapi_client.models.data_computed_get_dto.DataComputedGetDTO(
                        date = '2020-08-21T00:00+01:00', 
                        value = 8.6, )
                    ]
            )
        else:
            return DataSerieGetDTO(
        )
        """

    def testDataSerieGetDTO(self):
        """Test DataSerieGetDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
