# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.4.7-rdg
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.favorite_creation_dto import FavoriteCreationDTO

class TestFavoriteCreationDTO(unittest.TestCase):
    """FavoriteCreationDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FavoriteCreationDTO:
        """Test FavoriteCreationDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FavoriteCreationDTO`
        """
        model = FavoriteCreationDTO()
        if include_optional:
            return FavoriteCreationDTO(
                type = '',
                uri = ''
            )
        else:
            return FavoriteCreationDTO(
        )
        """

    def testFavoriteCreationDTO(self):
        """Test FavoriteCreationDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
