# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.4.7-rdg
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.facility_named_dto import FacilityNamedDTO

class TestFacilityNamedDTO(unittest.TestCase):
    """FacilityNamedDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FacilityNamedDTO:
        """Test FacilityNamedDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FacilityNamedDTO`
        """
        model = FacilityNamedDTO()
        if include_optional:
            return FacilityNamedDTO(
                uri = 'http://opensilex.dev/greenHouseA',
                name = 'greenHouseA'
            )
        else:
            return FacilityNamedDTO(
        )
        """

    def testFacilityNamedDTO(self):
        """Test FacilityNamedDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
