# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.4.7-rdg
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.uri_search_api import UriSearchApi


class TestUriSearchApi(unittest.TestCase):
    """UriSearchApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UriSearchApi()

    def tearDown(self) -> None:
        pass

    def test_search_by_uri(self) -> None:
        """Test case for search_by_uri

        Get a list of objects that match the passed URI
        """
        pass


if __name__ == '__main__':
    unittest.main()
