# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.4.7-rdg
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.br_apiv1_study_dto import BrAPIv1StudyDTO

class TestBrAPIv1StudyDTO(unittest.TestCase):
    """BrAPIv1StudyDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BrAPIv1StudyDTO:
        """Test BrAPIv1StudyDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BrAPIv1StudyDTO`
        """
        model = BrAPIv1StudyDTO()
        if include_optional:
            return BrAPIv1StudyDTO(
                active = '',
                additional_info = {
                    'key' : ''
                    },
                common_crop_name = '',
                documentation_url = '',
                end_date = '',
                location_db_id = '',
                location_name = '',
                program_db_id = '',
                program_name = '',
                start_date = '',
                study_db_id = '',
                study_name = '',
                study_type_db_id = '',
                study_type_name = '',
                trial_db_id = '',
                trial_name = '',
                seasons = [
                    openapi_client.models.br_apiv1_season_dto.BrAPIv1SeasonDTO(
                        season = '', 
                        season_db_id = '', 
                        year = '', )
                    ]
            )
        else:
            return BrAPIv1StudyDTO(
        )
        """

    def testBrAPIv1StudyDTO(self):
        """Test BrAPIv1StudyDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
