# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.4.7-rdg
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.document_get_dto import DocumentGetDTO

class TestDocumentGetDTO(unittest.TestCase):
    """DocumentGetDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DocumentGetDTO:
        """Test DocumentGetDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DocumentGetDTO`
        """
        model = DocumentGetDTO()
        if include_optional:
            return DocumentGetDTO(
                uri = 'http://opensilex.dev/set/documents#ProtocolExperimental',
                publisher = openapi_client.models.user_get_dto.UserGetDTO(
                    uri = 'http://opensilex.dev/users#jean.michel.inrae', 
                    email = 'jean.michel@example.com', 
                    language = 'en', 
                    admin = False, 
                    first_name = 'Jean', 
                    last_name = 'Michel', 
                    linked_person = 'http://opensilex.dev/person#Jean.Michel.mistea', 
                    enable = True, 
                    favorites = test, ),
                publication_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                identifier = 'doi:10.1340/309registries',
                rdf_type = 'http://www.opensilex.org/vocabulary/oeso#ScientificDocument',
                rdf_type_name = '',
                title = 'title',
                var_date = '2020-06-01',
                description = 'description',
                targets = http://opensilex.dev/opensilex/id/variables/v001,
                authors = Author name,
                language = 'fr',
                format = 'jpg',
                keywords = keyword,
                deprecated = False,
                source = ''
            )
        else:
            return DocumentGetDTO(
        )
        """

    def testDocumentGetDTO(self):
        """Test DocumentGetDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
