# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.4.7-rdg
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.documents_api import DocumentsApi


class TestDocumentsApi(unittest.TestCase):
    """DocumentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DocumentsApi()

    def tearDown(self) -> None:
        pass

    def test_count_documents(self) -> None:
        """Test case for count_documents

        Count documents
        """
        pass

    def test_create_document(self) -> None:
        """Test case for create_document

        Add a document
        """
        pass

    def test_delete_document(self) -> None:
        """Test case for delete_document

        Delete a document
        """
        pass

    def test_get_document_file(self) -> None:
        """Test case for get_document_file

        Get document
        """
        pass

    def test_get_document_metadata(self) -> None:
        """Test case for get_document_metadata

        Get document's description
        """
        pass

    def test_search_documents(self) -> None:
        """Test case for search_documents

        Search documents
        """
        pass

    def test_update_document(self) -> None:
        """Test case for update_document

        Update document's description
        """
        pass


if __name__ == '__main__':
    unittest.main()
