# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.4.7-rdg
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.site_get_dto import SiteGetDTO

class TestSiteGetDTO(unittest.TestCase):
    """SiteGetDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SiteGetDTO:
        """Test SiteGetDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SiteGetDTO`
        """
        model = SiteGetDTO()
        if include_optional:
            return SiteGetDTO(
                uri = '',
                rdf_type = '',
                rdf_type_name = '',
                publisher = openapi_client.models.user_get_dto.UserGetDTO(
                    uri = 'http://opensilex.dev/users#jean.michel.inrae', 
                    email = 'jean.michel@example.com', 
                    language = 'en', 
                    admin = False, 
                    first_name = 'Jean', 
                    last_name = 'Michel', 
                    linked_person = 'http://opensilex.dev/person#Jean.Michel.mistea', 
                    enable = True, 
                    favorites = test, ),
                publication_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                name = '',
                address = openapi_client.models.site_address_dto.SiteAddressDTO(
                    country_name = '', 
                    locality = '', 
                    postal_code = '', 
                    region = '', 
                    street_address = '', 
                    readable_address = '', ),
                organizations = [
                    openapi_client.models.named_resource_dto_organization_model.NamedResourceDTOOrganizationModel(
                        uri = '', 
                        name = '', 
                        rdf_type = '', 
                        rdf_type_name = '', 
                        publication_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        last_updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                facilities = [
                    openapi_client.models.named_resource_dto_facility_model.NamedResourceDTOFacilityModel(
                        uri = '', 
                        name = '', 
                        rdf_type = '', 
                        rdf_type_name = '', 
                        publication_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        last_updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                groups = [
                    openapi_client.models.named_resource_dto_group_model.NamedResourceDTOGroupModel(
                        uri = '', 
                        name = '', 
                        rdf_type = '', 
                        rdf_type_name = '', 
                        publication_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        last_updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                geometry = {"coordinates":[43.618316,3.856912],"type":"Point"},
                description = ''
            )
        else:
            return SiteGetDTO(
        )
        """

    def testSiteGetDTO(self):
        """Test SiteGetDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
