# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.4.7-rdg
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.br_apiv1_call_list_response import BrAPIv1CallListResponse

class TestBrAPIv1CallListResponse(unittest.TestCase):
    """BrAPIv1CallListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BrAPIv1CallListResponse:
        """Test BrAPIv1CallListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BrAPIv1CallListResponse`
        """
        model = BrAPIv1CallListResponse()
        if include_optional:
            return BrAPIv1CallListResponse(
                metadata = openapi_client.models.metadata_dto.MetadataDTO(
                    pagination = openapi_client.models.pagination_dto.PaginationDTO(
                        page_size = 56, 
                        current_page = 56, 
                        total_count = 56, 
                        total_pages = 56, 
                        limit_count = 56, 
                        has_next_page = True, ), 
                    status = [
                        openapi_client.models.status_dto.StatusDTO(
                            message = '', 
                            translation_key = '', 
                            translation_values = {
                                'key' : ''
                                }, 
                            level = 'ERROR', )
                        ], 
                    datafiles = [
                        ''
                        ], ),
                result = openapi_client.models.brapi_data_response_part_list_br_apiv1_call_dto.BrapiDataResponsePartListBrAPIv1CallDTO(
                    data = [
                        openapi_client.models.br_apiv1_call_dto.BrAPIv1CallDTO(
                            call = '', 
                            data_types = [
                                ''
                                ], 
                            methods = [
                                ''
                                ], 
                            versions = [
                                ''
                                ], )
                        ], )
            )
        else:
            return BrAPIv1CallListResponse(
        )
        """

    def testBrAPIv1CallListResponse(self):
        """Test BrAPIv1CallListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
