# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.4.7-rdg
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.site_creation_dto import SiteCreationDTO

class TestSiteCreationDTO(unittest.TestCase):
    """SiteCreationDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SiteCreationDTO:
        """Test SiteCreationDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SiteCreationDTO`
        """
        model = SiteCreationDTO()
        if include_optional:
            return SiteCreationDTO(
                uri = '',
                rdf_type = '',
                name = '',
                address = openapi_client.models.site_address_dto.SiteAddressDTO(
                    country_name = '', 
                    locality = '', 
                    postal_code = '', 
                    region = '', 
                    street_address = '', 
                    readable_address = '', ),
                organizations = [
                    ''
                    ],
                facilities = [
                    ''
                    ],
                groups = [
                    ''
                    ],
                description = '',
                rdf_type_name = '',
                publication_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return SiteCreationDTO(
        )
        """

    def testSiteCreationDTO(self):
        """Test SiteCreationDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
