# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.4.7-rdg
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.br_apiv1_season_dto import BrAPIv1SeasonDTO

class TestBrAPIv1SeasonDTO(unittest.TestCase):
    """BrAPIv1SeasonDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BrAPIv1SeasonDTO:
        """Test BrAPIv1SeasonDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BrAPIv1SeasonDTO`
        """
        model = BrAPIv1SeasonDTO()
        if include_optional:
            return BrAPIv1SeasonDTO(
                season = '',
                season_db_id = '',
                year = ''
            )
        else:
            return BrAPIv1SeasonDTO(
        )
        """

    def testBrAPIv1SeasonDTO(self):
        """Test BrAPIv1SeasonDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
