# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.4.7-rdg
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.dashboard_config_dto import DashboardConfigDTO

class TestDashboardConfigDTO(unittest.TestCase):
    """DashboardConfigDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DashboardConfigDTO:
        """Test DashboardConfigDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DashboardConfigDTO`
        """
        model = DashboardConfigDTO()
        if include_optional:
            return DashboardConfigDTO(
                show_metrics = True,
                graph1 = openapi_client.models.graph_config_dto.GraphConfigDTO(
                    variable = '', 
                    data_location_informations = '', ),
                graph2 = openapi_client.models.graph_config_dto.GraphConfigDTO(
                    variable = '', 
                    data_location_informations = '', ),
                graph3 = openapi_client.models.graph_config_dto.GraphConfigDTO(
                    variable = '', 
                    data_location_informations = '', )
            )
        else:
            return DashboardConfigDTO(
        )
        """

    def testDashboardConfigDTO(self):
        """Test DashboardConfigDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
