# coding: utf-8

"""
    OpenSilex API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.4.7-rdg
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.method_get_dto import MethodGetDTO

class TestMethodGetDTO(unittest.TestCase):
    """MethodGetDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MethodGetDTO:
        """Test MethodGetDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MethodGetDTO`
        """
        model = MethodGetDTO()
        if include_optional:
            return MethodGetDTO(
                uri = 'http://opensilex.dev/set/variables/method/ImageAnalysis',
                name = 'ImageAnalysis'
            )
        else:
            return MethodGetDTO(
        )
        """

    def testMethodGetDTO(self):
        """Test MethodGetDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
